### ISSUE TITLE
questions about androidaps note

### ISSUE THREAD

**Issue by KelvinKramp** [openaps/docs#1586]
In the documentation I read: 
"Caution for AndroidAPS users: Currently, the master oref0 version with Autotune does not parse AndroidAPS entries correctly. You must set AndroidAPS to upload all temp basals as “absolute” rates, instead of %, and use the dev branch of oref0. If you do not do both of these things, your results will be wrong! Future versions of Autotune will allow using AndroidAPS data as long as the option to upload temp basals as absolute values instead of / in addition to percent is enabled in AndroidAPS. "

Is the latest version during writing 3.1.0.3. one of the future versions referred to above? 

If not, where in AndroidAPS can you change the setting to "absolute" rates if we should still take care of this?  

If yes, can I remove this text and make a PR?

**Comment by scottleibrand** [comment]
I don't use AndroidAPS, so don't know whether AndroidAPS uploads absolute values by default now. Can you tell by looking at your Nightscout treatments collection (/api/v1/treatments.json)?

An OpenAPS temp basal record looks something like this (I removed the timestamps and id fields). The important part is the absolute rate (in U/hr): that can't just be a percentage.

```
{
duration: 30,
raw_duration: {
_type: "TempBasalDuration",
duration (min): 30
},
absolute: 1.6,
rate: 1.6,
raw_rate: {
_type: "TempBasal",
temp: "absolute",
rate: 1.6
},
eventType: "Temp Basal",
medtronic: "mm://openaps/mm-format-ns-treatments/Temp Basal",
created_at: "2023-01-16T03:52:57.000Z",
carbs: null,
insulin: null
},
```

We can definitely remove the "use the dev branch of oref0" note: we've had several releases since then.

**Comment by KelvinKramp** [comment]
I get the following json:
[
   {
      "_id":"",
      "created_at":"",
      "enteredBy":"openaps://AndroidAPS",
      "eventType":"Temp Basal",
      "isValid":true,
      "duration":30,
      "durationInMilliseconds":1800000,
      "type":"NORMAL",
      **"rate":0.18,**
      "percent":-70,
      "carbs":null,
      "insulin":null
   },

In androidAPS i see the following on the loop tab: 
![Blank diagram](https://user-images.githubusercontent.com/76985447/212659262-23186fd1-b215-4a61-a050-4880b2432486.jpeg)

AndroidAPS seems to upload absolute values to nightscout. Ill create a PR.
