### ISSUE TITLE
ubuntu linux based install

### ISSUE THREAD

**Issue by ehwest** [openaps/docs#466]
I'm using a ubuntu linux desktop system (command line only),
I also have an 8 Gig SD card I'd like to use.
Can you add information on how to burn the SD card so the intel edison boots from that?

**Comment by scottleibrand** [comment]
This is a more general Edison question that might be better asked in Intel's Edison forum. Or you could try in Gitter to see if anyone happens to know what would be required. I don't think anyone typically uses an SD card as a boot drive for the Edison, though. What's your goal with using that instead of the Edison's onboard storage?

**Comment by ehwest** [comment]
OK, I found that if you want intel edison to boot from an SD card, you have to flash into the intel edison device the choice of the new boot media.   This customization of the intel edison spoils the solution.  Presumably you'd want to boot from an SD card because the SD cards can be mass produced and the intel-edison devices out of the box would boot and run the SD card.  This presumably would save a lot of time when building a lot of intel edison devices.   But if the intel edison devices have to be flashed to use the SD card, well, its pointless.  The whole idea was to eliminate one or two flashing of the intel edison, which can be a fairly tedious and error-prone process.  Worse, there are several ways to make a mistake in doing this, some of which can brick the intel edison device.
